name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Build Docker image
      run: |
          docker build -t devolux/route-circle-api:latest .
          docker tag devolux/route-circle-api:latest devolux/route-circle-api:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push devolux/route-circle-api:latest

    - name: Send HTTP Request to Portainer Docker
      run: |
        curl -X POST -d '{}' https://docker.devolux.nl/api/stacks/webhooks/66541ee7-6b96-43df-a130-25d820761e9c
